### ISSUE TITLE
Purpose of fp16.h install

### ISSUE THREAD

**Issue by xsacha** [Maratyszcza/FP16#12]
What is the purpose of the fp16.h (https://github.com/Maratyszcza/FP16/blob/master/include/fp16.h) install when it seems to only include fp16/fp16.h and (optionally) fp16/psimd.h?
It isn't in a subfolder and the user could just as easily include fp16/fp16.h themselves.

Should this actually be installed or was it only meant to be used for the benchmark/tests?

I couldn't see PSIMD_H defined anywhere so I assume it only includes it if the upstream header was already included.

**Comment by Maratyszcza** [comment]
FP16 can be installed as a header-only library, and several package managers in fact include it.
