### ISSUE TITLE
MSVC errors when using psimd

### ISSUE THREAD

**Issue by xsacha** [Maratyszcza/FP16#14]
fp16/psimd.h(14): error C2433: 'psimd_f32': '__forceinline' not permitted on data declarations [C:\projects\hunter-h4uji\_testing\_builds\vs-14-2015-sdk-8-1\boo.vcxproj]

See: https://ci.appveyor.com/project/xsacha/hunter-h4uji/builds/23144758/job/5x56s69avyxef1m3

Seems to be complaining about the usage of __forceinline when used in PSIMD_INTRINSIC for fp16/psimd.h

From here: https://social.msdn.microsoft.com/Forums/vstudio/en-US/94f27276-62c3-441a-9919-7114e77c67a4/errors-while-executing-vc-code?forum=vclanguage
It suggests including Windows.h will make such an error go away.

**Comment by Maratyszcza** [comment]
`psimd` dependency removed in 80bd3226c39086c1914c5499b23be97bbe268492
