### ISSUE TITLE
Ubuntu 18.04 linux stuck on test 3

### ISSUE THREAD

**Issue by breznak** [Maratyszcza/FP16#15]
hi, I'm first time testing this repo, 

just `cloned, cmake . , make -j `

running make tests gets stuck on test 3: 

> FP16$ make test
Running tests...
Test project /mnt/store/devel/FP16
Start 1: ieee-to-fp32-bits
1/7 Test #1: ieee-to-fp32-bits ................   Passed    0.01 sec
Start 2: ieee-to-fp32-value
2/7 Test #2: ieee-to-fp32-value ...............   Passed    0.01 sec
Start 3: ieee-from-fp32-value
^CMakefile:106: recipe for target 'test' failed
make: *** [test] Přerušení (SIGINT)

**Comment by Maratyszcza** [comment]
This test checks all `2**32` possible input values, so most likely you just need to wait for longer.
