### ISSUE TITLE
patch for fixing i686 build

### ISSUE THREAD

**Issue by cdluminate** [Maratyszcza/FP16#20]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=996702

Let me quote the message:
```
Dear Maintainer,

the function fp16_ieee_from_fp32_value() fails to pass tests on i386 arch,
resulting in missing packages https://buildd.debian.org/status/package.php?p=fp16

I think the problem here is implicit usage of double type at include/fp16/fp16.h:231.
The patch should fix that.
```

And the patch is available here: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=996702;filename=ia32.patch;msg=5

**Comment by Maratyszcza** [comment]
Thank you for reporting, fixed in f0bd4b9b114d103d5d134944db9b213401320dd5
