### ISSUE TITLE
Build with VS

### ISSUE THREAD

**Issue by ayermolo** [Maratyszcza/FP16#8]
Visual studio doesn't support __builtin_clz. 
Can something like below be added to fp16.h?

#ifdef _MSC_VER
#define NOMINMAX
#include "windows.h"
#include <intrin.h>
uint32_t __inline clz(uint32_t value) {
  DWORD count = 0;
  return (_BitScanReverse(&count, value)) ? 31 - count : 32;
}
#define __builtin_clz(x) clz(x)
#endif

**Comment by Maratyszcza** [comment]
Are you using the most recent version of FP16? VS compatibility was added in 34d4bf01bbf7376f2baa71b8fa148b18524d45cf

**Comment by ayermolo** [comment]
Ah sorry. Didn't notice the change after merge with latest. Thanks!
